version: "2"

services:
    flask:
        build: ./app
        hostname: backend
        ports:
            - 80:8000
        volumes:
            - ./app:/var/app
            - ./static:/var/static
